- name: Ensure Go environment is set
  shell: source /etc/profile
  args:
    executable: /bin/bash

- name: Create project directory
  file:
    path: "{{ playbook_dir }}/go_project"
    state: directory
    mode: "0755"

- name: Clone the GitHub repository
  git:
    repo: "https://github.com/MikkoVasankari/mankka.git"
    dest: "{{ playbook_dir }}/go_project"
    version: "main"
    force: yes

- name: Build Go binary
  command: go build -o {{ playbook_dir }}/mankka .
  args:
    chdir: "{{ playbook_dir }}/go_project"
  environment:
    PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
