name: Build Executable from Go project

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v -o mankka/ ./...

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v3
      with:
        name: mankka
        path: ./mankka
